Update practice.yml

diff --git a/.github/workflows/practice.yml b/.github/workflows/practice.yml
--- a/.github/workflows/practice.yml
+++ b/.github/workflows/practice.yml
@@ -42,6 +42,25 @@ jobs:
           npm test
           sleep 1
           echo "Test has finished with exit code $?"
+
+  Build_Stage:
+    runs-on: ubuntu-latest
+    needs: My_setup
+    steps:
+      - name: Checkout Repo
+        uses: actions/checkout@v4
+      - name: Setting up node
+        uses: actions/setup-node@v6.5.0
+        with:
+          node-version: 22.x
+      - name: Installing Depend
+        run: |
+          npm install
+          if [ $? -eq 0 ];then
+            echo "Tesing successfully done"
+          else
+            echo "An Error happened"
+          fi
           
      # - name: checking file exists
      #  run: |
